encoding: utf-8

plugins:
  - jekyll-regex-replace
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

title: sirva
description: ajiglaltuud
url: "https://visbaina.github.io/yyy"
tagline: ajiglaltuud
logo: "/static/img/logo.jpg"
keywords: hun, soyol, tuuj
author: sirva
footerText: '2025 sirva'

permalink: /:slug/
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
include:
  - pages
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

domainUrl: 'https://aaaarrrrvvvv.github.io'
baseurl: ''

google_analytics: ""

extClickEffect: true

extAdsense: false

extMath: false

extCount: false

