encoding: utf-8

plugins:
  - jekyll-regex-replace
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

title: Дөрвөн зуу
description: Дал
url: "https://aaaarrrrvvvv.github.io"
tagline: Арван хоёр
logo: "/static/img/logo.jpg"
keywords: 
author: 
footerText: 'Зүүн'

permalink: /:slug/
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
include:
  - pages
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

domainUrl: 'https://aaaarrrrvvvv.github.io'
baseurl: ''

google_analytics: ""

extClickEffect: true

extAdsense: false

extMath: false

extCount: false


